### ISSUE TITLE
Update to the latest version

### ISSUE THREAD

**Issue by pktiuk** [tsduck/hides-drivers#2]
According to [download page](http://www.hides.com.tw/downloads_eng.html) the latest version for Linux is v18.04.16.1 ([it950x_linux_v18.04.16.1.zip](https://www.dropbox.com/sh/zcrqdf5xrvfa4wz/AACib5Z7EBErqk35N-DZGt5Pa?dl=0)).

Are you going to provide this version with your patches?

**Comment by lelegard** [comment]
Hi @pktiuk 

Sorry for the late answers. The version 18.04.16.1 only fixes insufficient error checking. It does not integrate new features and does not support new kernels. Specifically, it does not compile on kernel 5.10 and above.

I have just released an update, based on 18.04.16.1 with fixes for recent kernels and backport of the blocking write features.
